[phases.setup]
commands = [
    "npm install" # Install dependencies
]

[phases.build]
commands = [
    "npm run build" # Build the Vue project
]

[phases.start]
commands = [
    "npm run serve" # Serve the app for development
]
[build]
node_version = "20.18.0"
